/**
 * 周易六十四卦典籍库 (文王金钱课·正统文王六爻)
 * 包含：六十四卦卦名、上下卦、卦画、文王卦辞、孔子大象传、文王金钱课古籍断诗、古典卦象典故与现代转译
 */

export interface HexagramData {
  id: number
  name: string            // 卦名，如：乾为天
  upperTrigram: string    // 上卦，如：乾
  lowerTrigram: string    // 下卦，如：乾
  binary: string          // 六爻二进制自下而上 (1为阳, 0为阴)，如 '111111'
  symbol: string          // 卦符，如 ䷀
  nature: string          // 卦象自然，如：天行纯阳
  classicQuote: string    // 文王金钱课典故，如：困龙得水
  verse: string           // 文王金钱课古籍原断诗 (四句)
  guaci: string           // 文王卦辞原文
  daxiang: string         // 孔子《大象传》原文
  luckLevel: 'supreme' | 'great' | 'medium' | 'small' | 'peace'
  luckTitle: string       // 如：大吉 · 势不可挡
  interpretation: string  // 灵机详释
  yi: string              // 今日宜
  ji: string              // 今日忌
  luckyNumber: number
  luckyColor: string
  luckyCompass: string
  stars: { fortune: number; career: number; wealth: number; vitality: number }
}

// 八经卦二进制编码 (自下而上 3位)
// 乾(天): 111, 兑(泽): 110, 离(火): 101, 震(雷): 100, 巽(风): 011, 坎(水): 010, 艮(山): 001, 坤(地): 000
// 注：传统画卦自初爻至三爻：
// 乾☰: 1,1,1 -> '111'
// 兑☱(上缺): 初阳,二阳,上阴 -> '110'
// 离☲(中虚): 初阳,二阴,上阳 -> '101'
// 震☳(仰盂): 初阳,二阴,上阴 -> '100'
// 巽☴(下断): 初阴,二阳,上阳 -> '011'
// 坎☵(中满): 初阴,二阳,上阴 -> '010'
// 艮☶(覆碗): 初阴,二阴,上阳 -> '001'
// 坤☷: 初阴,二阴,上阴 -> '000'

export const TRIGRAM_MAP: Record<string, { name: string; element: string; symbol: string }> = {
  '111': { name: '乾', element: '天', symbol: '☰' },
  '110': { name: '兑', element: '泽', symbol: '☱' },
  '101': { name: '离', element: '火', symbol: '☲' },
  '100': { name: '震', element: '雷', symbol: '☳' },
  '011': { name: '巽', element: '风', symbol: '☴' },
  '010': { name: '坎', element: '水', symbol: '☵' },
  '001': { name: '艮', element: '山', symbol: '☶' },
  '000': { name: '坤', element: '地', symbol: '☷' }
}

// 六十四卦完整典籍字典
export const HEXAGRAM_DATABASE: Record<string, HexagramData> = {
  // 1. 乾为天 111 111
  '111111': {
    id: 1,
    name: '乾为天',
    upperTrigram: '乾',
    lowerTrigram: '乾',
    binary: '111111',
    symbol: '䷀',
    nature: '天行纯阳',
    classicQuote: '困龙得水',
    verse: '蛟龙久困在渊中，一日冲霄起御风。莫道时乖无际遇，前程万里显英雄。',
    guaci: '元亨，利贞。',
    daxiang: '天行健，君子以自强不息。',
    luckLevel: 'supreme',
    luckTitle: '上上大吉 · 龙跃九霄',
    interpretation: '大哉乾元，万物资始。极刚极健，今日浩然正气充盈，行事果断笃定，攻关克难无往不利。',
    yi: '发版上线、重构攻坚、开拓新局、请客饮茶',
    ji: '犹豫退缩、自我怀疑、过早松懈',
    luckyNumber: 9,
    luckyColor: '琥珀金',
    luckyCompass: '西北',
    stars: { fortune: 5, career: 5, wealth: 5, vitality: 5 }
  },
  // 2. 坤为地 000 000
  '000000': {
    id: 2,
    name: '坤为地',
    upperTrigram: '坤',
    lowerTrigram: '坤',
    binary: '000000',
    symbol: '䷁',
    nature: '地势柔顺',
    classicQuote: '饿虎得食',
    verse: '肥羊失群入山岗，饿虎逢之把口张。适口充肠心欢喜，卦若占此大吉昌。',
    guaci: '元亨，利牝马之贞。君子有攸往，先迷后得主。',
    daxiang: '地势坤，君子以厚德载物。',
    luckLevel: 'great',
    luckTitle: '上吉 · 厚德载物',
    interpretation: '至哉坤元，万物资生。以柔克刚，包容笃实。今日宜沉潜深耕，蓄力积累，不急于一时争先。',
    yi: '代码重构、沉淀文档、查缺补漏、早睡养神',
    ji: '冒进争强、心浮气躁、盲目下注',
    luckyNumber: 8,
    luckyColor: '玄青墨',
    luckyCompass: '西南',
    stars: { fortune: 5, career: 4, wealth: 4, vitality: 5 }
  },
  // 3. 水雷屯 100 010 (下震100，上坎010 -> 100010)
  '100010': {
    id: 3,
    name: '水雷屯',
    upperTrigram: '坎',
    lowerTrigram: '震',
    binary: '100010',
    symbol: '䷂',
    nature: '春雷破冻',
    classicQuote: '乱丝无头',
    verse: '风刮乱丝不见头，颠三倒四使人愁。慢慢梳理终有绪，急躁难成莫强求。',
    guaci: '元亨，利贞。勿用有攸往，利建侯。',
    daxiang: '云雷，屯；君子以经纶。',
    luckLevel: 'medium',
    luckTitle: '中吉 · 万物初萌',
    interpretation: '屯者，物之初生也。万事开头难，虽有初创之艰阻，但生机正盛，循序渐进必迎朝阳。',
    yi: '梳理架构、厘清主线、循序渐进、耐心调试',
    ji: '急于求成、乱抓一把、半途而废',
    luckyNumber: 3,
    luckyColor: '松绿',
    luckyCompass: '正北',
    stars: { fortune: 3, career: 4, wealth: 3, vitality: 4 }
  },
  // 4. 山水蒙 010 001 (下坎010，上艮001 -> 010001)
  '010001': {
    id: 4,
    name: '山水蒙',
    upperTrigram: '艮',
    lowerTrigram: '坎',
    binary: '010001',
    symbol: '䷃',
    nature: '山下出泉',
    classicQuote: '小鬼拔河',
    verse: '幼芽出土见天日，泉水涓涓石下出。开蒙启智拜明师，虚怀若谷前途阔。',
    guaci: '亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。',
    daxiang: '山下出泉，蒙；君子以果行育德。',
    luckLevel: 'medium',
    luckTitle: '中吉 · 启蒙化境',
    interpretation: '蒙以养正，圣功也。今日利于求教解惑、虚心求学，向高人求教，迷雾自当豁然开朗。',
    yi: '向人请教、精读源码、温故知新、查阅文档',
    ji: '不懂装懂、主观臆断、盲目自大',
    luckyNumber: 7,
    luckyColor: '月魄白',
    luckyCompass: '东北',
    stars: { fortune: 3, career: 4, wealth: 3, vitality: 4 }
  },
  // 5. 水天需 111 010 (下乾111，上坎010 -> 111010)
  '111010': {
    id: 5,
    name: '水天需',
    upperTrigram: '坎',
    lowerTrigram: '乾',
    binary: '111010',
    symbol: '䷄',
    nature: '云上于天',
    classicQuote: '明珠出土',
    verse: '明珠土埋日已久，今朝见天光芒陡。谋望求财皆遂意，走马扬鞭上坦途。',
    guaci: '有孚，光亨，贞吉。利涉大川。',
    daxiang: '云上于天，需；君子以饮食宴乐。',
    luckLevel: 'great',
    luckTitle: '上吉 · 守正待时',
    interpretation: '需者，待也。云聚天际甘霖将至，当前最重蓄养从容。从容备战，东风至时必当大展宏图。',
    yi: '养精蓄锐、品茗听雨、静心等待、梳理计划',
    ji: '焦虑催促、冲动冒进、深夜内耗',
    luckyNumber: 5,
    luckyColor: '天青色',
    luckyCompass: '西北',
    stars: { fortune: 4, career: 4, wealth: 4, vitality: 5 }
  },
  // 6. 天水讼 010 111 (下坎010，上乾111 -> 010111)
  '010111': {
    id: 6,
    name: '天水讼',
    upperTrigram: '乾',
    lowerTrigram: '坎',
    binary: '010111',
    symbol: '䷅',
    nature: '天水违行',
    classicQuote: '二人争路',
    verse: '二人争路未肯让，占讼必伤两不成。退后一步天地宽，和衷共济百福生。',
    guaci: '有孚，窒惕，中吉，终凶。利见大人，不利涉大川。',
    daxiang: '天与水违行，讼；君子以作事谋始。',
    luckLevel: 'peace',
    luckTitle: '吉平 · 和以息争',
    interpretation: '讼不可长。争讼伤和，退一步海阔天空。今日行事宜求同存异，克制口舌意气，慎始善终。',
    yi: '换位思考、克制争辩、备份数据、核实契约',
    ji: '意气用事、网上论战、情绪抬杠',
    luckyNumber: 6,
    luckyColor: '灰蓝',
    luckyCompass: '正西',
    stars: { fortune: 3, career: 3, wealth: 3, vitality: 4 }
  },
  // 7. 地水师 010 000 (下坎010，上坤000 -> 010000)
  '010000': {
    id: 7,
    name: '地水师',
    upperTrigram: '坤',
    lowerTrigram: '坎',
    binary: '010000',
    symbol: '䷆',
    nature: '地中有水',
    classicQuote: '马到成功',
    verse: '将帅用兵有纪律，出师伐罪定干戈。吉人自有天相助，马到成功奏凯歌。',
    guaci: '贞，丈人，吉无咎。',
    daxiang: '地中有水，师；君子以容民畜众。',
    luckLevel: 'great',
    luckTitle: '上吉 · 师出有名',
    interpretation: '师出以律，失律凶也。严谨组织与自律执行是今日制胜关键，纪律分明、步调一致必克难题。',
    yi: '团队协同、统筹规划、严格自律、执行方案',
    ji: '散漫无序、各自为战、越权行事',
    luckyNumber: 7,
    luckyColor: '军绿色',
    luckyCompass: '正北',
    stars: { fortune: 4, career: 5, wealth: 4, vitality: 4 }
  },
  // 8. 水地比 000 010 (下坤000，上坎010 -> 000010)
  '000010': {
    id: 8,
    name: '水地比',
    upperTrigram: '坎',
    lowerTrigram: '坤',
    binary: '000010',
    symbol: '䷇',
    nature: '地上有水',
    classicQuote: '船得顺风',
    verse: '顺水行舟用短蒿，百般谋望不费劳。贵人相助逢吉兆，前程坦荡乐陶陶。',
    guaci: '吉。原筮元永贞，无咎。不宁方来，后夫凶。',
    daxiang: '地上有水，比；先王以建万国，亲诸侯。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 和睦相亲',
    interpretation: '比者，辅也，相亲也。水附于地，亲密无间。今日贵人缘极佳，人际融洽，合力成大事。',
    yi: '拜访好友、团队团建、商务合作、结交良师',
    ji: '孤僻冷漠、疑心猜忌、迟疑不决',
    luckyNumber: 8,
    luckyColor: '碧海蓝',
    luckyCompass: '正南',
    stars: { fortune: 5, career: 5, wealth: 4, vitality: 5 }
  },
  // 9. 风天小畜 111 011 (下乾111，上巽011 -> 111011)
  '111011': {
    id: 9,
    name: '风天小畜',
    upperTrigram: '巽',
    lowerTrigram: '乾',
    binary: '111011',
    symbol: '䷈',
    nature: '风行天上',
    classicQuote: '密云不雨',
    verse: '苗逢久旱渴望霖，今日阴云遍布林。虽然未降倾盆雨，润物无声在此行。',
    guaci: '亨。密云不雨，自我西郊。',
    daxiang: '风行天上，小畜；君子以懿文德。',
    luckLevel: 'medium',
    luckTitle: '中吉 · 循序渐进',
    interpretation: '小蓄小积，蓄养微力。当前力量正在温和凝聚中，不必强求大成，细水长流亦能穿石。',
    yi: '细节打磨、优化体验、小步快跑、阅读随笔',
    ji: '冒进贪大、孤注一掷、急躁暴怒',
    luckyNumber: 4,
    luckyColor: '翠青色',
    luckyCompass: '东南',
    stars: { fortune: 3, career: 4, wealth: 3, vitality: 4 }
  },
  // 10. 天泽履 110 111 (下兑110，上乾111 -> 110111)
  '110111': {
    id: 10,
    name: '天泽履',
    upperTrigram: '乾',
    lowerTrigram: '兑',
    binary: '110111',
    symbol: '䷉',
    nature: '上天下泽',
    classicQuote: '凤鸣岐山',
    verse: '凤鸣岐山出圣贤，谋望求财步步全。履霜坚冰知谨畏，险道从容亦是仙。',
    guaci: '履虎尾，不咥人，亨。',
    daxiang: '上天下泽，履；君子以辨上下，安民志。',
    luckLevel: 'great',
    luckTitle: '上吉 · 谨礼而行',
    interpretation: '履虎尾而不咥人，心诚敬畏也。处事谦逊谨饬，以礼待人，即便面临严苛挑战亦能安然化解。',
    yi: '谨言慎行、规范流程、礼貌沟通、严格测试',
    ji: '狂妄自大、违规操作、盲目冒险',
    luckyNumber: 1,
    luckyColor: '银白色',
    luckyCompass: '西北',
    stars: { fortune: 4, career: 5, wealth: 4, vitality: 4 }
  },
  // 11. 地天泰 111 000 (下乾111，上坤000 -> 111000)
  '111000': {
    id: 11,
    name: '地天泰',
    upperTrigram: '坤',
    lowerTrigram: '乾',
    binary: '111000',
    symbol: '䷊',
    nature: '天地交泰',
    classicQuote: '喜报三元',
    verse: '学问满腹入场中，果然金榜题名红。喜气洋洋门庭耀，步步高升位三公。',
    guaci: '小往大来，吉，亨。',
    daxiang: '天地交，泰；后以财成天地之道，辅相天地之宜，以左右民。',
    luckLevel: 'supreme',
    luckTitle: '上上大吉 · 三阳开泰',
    interpretation: '天地交而万物通。阳升阴降，万象和美，沟通顺达无滞，诸事顺遂，正是大展宏图之盛运。',
    yi: '项目交付、技术分享、结交良友、户外踏青',
    ji: '自我封闭、情绪抬杠、拖沓消极',
    luckyNumber: 3,
    luckyColor: '朱砂红',
    luckyCompass: '东北',
    stars: { fortune: 5, career: 5, wealth: 5, vitality: 5 }
  },
  // 12. 天地否 000 111 (下坤000，上乾111 -> 000111)
  '000111': {
    id: 12,
    name: '天地否',
    upperTrigram: '乾',
    lowerTrigram: '坤',
    binary: '000111',
    symbol: '䷋',
    nature: '天地不交',
    classicQuote: '虎落深坑',
    verse: '虎落深坑步难移，求谋难遂事迟疑。守正藏锋宜待吉，免得招愆惹是非。',
    guaci: '否之匪人，不利君子贞，大往小来。',
    daxiang: '天地不交，否；君子以俭德辟难，不可荣以禄。',
    luckLevel: 'peace',
    luckTitle: '吉平 · 守正藏锋',
    interpretation: '天地不交，闭塞成否。当此时运，宜内敛克制，休养生息，以静制动，安度潜伏期。',
    yi: '守拙保身、整理旧档、早睡休息、少说多听',
    ji: '激进行事、大额交易、与人争锋',
    luckyNumber: 2,
    luckyColor: '暗曜黑',
    luckyCompass: '西南',
    stars: { fortune: 2, career: 3, wealth: 2, vitality: 4 }
  },
  // 13. 天火同人 101 111 (下离101，上乾111 -> 101111)
  '101111': {
    id: 13,
    name: '天火同人',
    upperTrigram: '乾',
    lowerTrigram: '离',
    binary: '101111',
    symbol: '䷌',
    nature: '天与火同',
    classicQuote: '仙人指路',
    verse: '仙人指路得真传，四海同心结善缘。聚智聚力图大事，光前裕后福长绵。',
    guaci: '同人于野，亨。利涉大川，利君子贞。',
    daxiang: '天与火，同人；君子以类族辨物。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 志同道合',
    interpretation: '同人于野，通天下之志。开诚布公，广纳贤才，凝聚共识。今日利于协同共创、开源开放。',
    yi: '开源分享、团队脑暴、同侪交流、聚餐闲谈',
    ji: '拉帮结派、偏狭自闭、计较小利',
    luckyNumber: 7,
    luckyColor: '丹霞赤',
    luckyCompass: '正南',
    stars: { fortune: 5, career: 5, wealth: 4, vitality: 5 }
  },
  // 14. 火天大有 111 101 (下乾111，上离101 -> 111101)
  '111101': {
    id: 14,
    name: '火天大有',
    upperTrigram: '离',
    lowerTrigram: '乾',
    binary: '111101',
    symbol: '䷍',
    nature: '日丽中天',
    classicQuote: '砍树摸雀',
    verse: '砍倒枯树摸雀儿，得来全不费工夫。谋望求财皆遂意，走马扬鞭上坦途。',
    guaci: '元亨。',
    daxiang: '火在天上，大有；君子以遏恶扬善，顺天休命。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 丰硕满载',
    interpretation: '火在天上，大有光彩。福星高照，名利两旺。此前付出将迎来丰盈回响，宜光明磊落行大事。',
    yi: '公开成果、发表佳作、领奖晋升、添置设备',
    ji: '小富即安、孤芳自赏、骄横懈怠',
    luckyNumber: 1,
    luckyColor: '赤金黄',
    luckyCompass: '正南',
    stars: { fortune: 5, career: 5, wealth: 5, vitality: 5 }
  },
  // 15. 地山谦 001 000 (下艮001，上坤000 -> 001000)
  '001000': {
    id: 15,
    name: '地山谦',
    upperTrigram: '坤',
    lowerTrigram: '艮',
    binary: '001000',
    symbol: '䷎',
    nature: '地中有山',
    classicQuote: '二人分金',
    verse: '二人分金笑颜开，谦和退让福自来。天道亏盈而益谦，君子抱朴远非灾。',
    guaci: '亨，君子有终。',
    daxiang: '地中有山，谦；君子以裒多益寡，称物平施。',
    luckLevel: 'great',
    luckTitle: '上吉 · 谦受益满',
    interpretation: '谦者，德之柄也。高山居于地底，大智若愚，谦逊受益。今日行事平易近人，必得广泛尊重赞赏。',
    yi: '虚心受教、平易待人、代码重构、静心默坐',
    ji: '自视甚高、傲慢逞强、抢占风头',
    luckyNumber: 5,
    luckyColor: '檀香褐',
    luckyCompass: '东北',
    stars: { fortune: 4, career: 4, wealth: 4, vitality: 5 }
  },
  // 16. 雷地豫 000 100 (下坤000，上震100 -> 000100)
  '000100': {
    id: 16,
    name: '雷地豫',
    upperTrigram: '震',
    lowerTrigram: '坤',
    binary: '000100',
    symbol: '䷏',
    nature: '雷出地奋',
    classicQuote: '青龙得位',
    verse: '青龙得位跃晴空，万木逢春发惠风。悦乐从容谋远略，功名富贵两从容。',
    guaci: '利建侯行师。',
    daxiang: '雷出地奋，豫；先王以作乐崇德，殷荐之上帝，以配祖考。',
    luckLevel: 'great',
    luckTitle: '上吉 · 悦豫从容',
    interpretation: '豫者，乐也，和也。雷出地奋，万物复苏欣喜。心情舒畅，保持乐观平和，自能心想事成。',
    yi: '听轻音乐、布置工位、品尝美食、聚会交流',
    ji: '沉溺享乐、拖延怠工、紧绷焦虑',
    luckyNumber: 3,
    luckyColor: '天水碧',
    luckyCompass: '正东',
    stars: { fortune: 4, career: 5, wealth: 4, vitality: 5 }
  },
  // 17. 泽雷随 100 110 (下震100，上兑110 -> 100110)
  '100110': {
    id: 17,
    name: '泽雷随',
    upperTrigram: '兑',
    lowerTrigram: '震',
    binary: '100110',
    symbol: '䷐',
    nature: '泽中有雷',
    classicQuote: '推车靠崖',
    verse: '推车靠崖步步坚，随波逐浪顺风帆。适时而动无违逆，任运腾挪自泰然。',
    guaci: '元亨利贞，无咎。',
    daxiang: '泽中有雷，随；君子以向晦入宴息。',
    luckLevel: 'medium',
    luckTitle: '中吉 · 随遇而安',
    interpretation: '随者，从也，顺也。顺应客观大势，不强求死板执念。随缘而行，因势利导，百事皆通。',
    yi: '顺应变化、调整计划、精简代办、静心安歇',
    ji: '固执死硬、盲目抗逆、钻牛角尖',
    luckyNumber: 8,
    luckyColor: '淡竹青',
    luckyCompass: '东南',
    stars: { fortune: 4, career: 4, wealth: 3, vitality: 4 }
  },
  // 18. 山风蛊 011 001 (下巽011，上艮001 -> 011001)
  '011001': {
    id: 18,
    name: '山风蛊',
    upperTrigram: '艮',
    lowerTrigram: '巽',
    binary: '011001',
    symbol: '䷑',
    nature: '山下有风',
    classicQuote: '抓钱入柜',
    verse: '积垢初除见清明，拨乱反正自条融。除陈布新展新颜，前程似锦福自生。',
    guaci: '元亨，利涉大川。先甲三日，后甲三日。',
    daxiang: '山下有风，蛊；君子以振民育德。',
    luckLevel: 'medium',
    luckTitle: '中吉 · 拨乱反正',
    interpretation: '蛊者，事也，坏极而求治也。面对历史遗留技术债务，正当快刀斩乱麻、大刀阔斧重整旗鼓。',
    yi: '重构老代码、清理垃圾文件、修复旧Bug、断舍离',
    ji: '拖沓包庇、因循守旧、得过且过',
    luckyNumber: 7,
    luckyColor: '秋叶黄',
    luckyCompass: '东北',
    stars: { fortune: 3, career: 4, wealth: 4, vitality: 4 }
  },
  // 19. 地泽临 110 000 (下兑110，上坤000 -> 110000)
  '110000': {
    id: 19,
    name: '地泽临',
    upperTrigram: '坤',
    lowerTrigram: '兑',
    binary: '110000',
    symbol: '䷒',
    nature: '地上有泽',
    classicQuote: '发政施仁',
    verse: '君王临政恤民情，万姓归心天下平。运际亨通多吉庆，家道兴隆万事呈。',
    guaci: '元，亨，利，贞。至于八月有凶。',
    daxiang: '泽上有地，临；君子以教思无穷，容保民无疆。',
    luckLevel: 'great',
    luckTitle: '上吉 · 亲临化境',
    interpretation: '临者，大也，深入也。阳气渐长，春意盎然。亲力亲为、深入第一线巡视探究，收获斐然。',
    yi: '实地调研、走查流程、督导进度、关心伙伴',
    ji: '纸上谈兵、遥控指挥、轻视隐患',
    luckyNumber: 2,
    luckyColor: '杏仁黄',
    luckyCompass: '正西',
    stars: { fortune: 4, career: 5, wealth: 4, vitality: 5 }
  },
  // 20. 风地观 000 011 (下坤000，上巽011 -> 000011)
  '000011': {
    id: 20,
    name: '风地观',
    upperTrigram: '巽',
    lowerTrigram: '坤',
    binary: '000011',
    symbol: '䷓',
    nature: '风行地上',
    classicQuote: '旱莲逢雨',
    verse: '观风察俗意从容，旱莲得雨发青葱。高瞻远瞩明大体，福禄随身喜重重。',
    guaci: '盥而不荐，有孚颙若。',
    daxiang: '风行地上，观；先王以省方，观民设教。',
    luckLevel: 'medium',
    luckTitle: '中吉 · 澄怀观道',
    interpretation: '观者，示也，瞻视也。居高临下，洞悉全局。退后一步观察全局架构，往往看清症结所在。',
    yi: '架构全景审视、反思复盘、静坐阅读、眺望远方',
    ji: '一叶障目、死扣细节、妄下断语',
    luckyNumber: 5,
    luckyColor: '松霜绿',
    luckyCompass: '东南',
    stars: { fortune: 3, career: 4, wealth: 3, vitality: 4 }
  },
  // 24. 地雷复 100 000 (下震100，上坤000 -> 100000)
  '100000': {
    id: 24,
    name: '地雷复',
    upperTrigram: '坤',
    lowerTrigram: '震',
    binary: '100000',
    symbol: '䷗',
    nature: '地中雷鸣',
    classicQuote: '夫妻迎门',
    verse: '马氏太公两分离，今朝相会喜开眉。一阳复始生机发，万象更新福自随。',
    guaci: '亨。出入无疾，朋来无咎。反复其道，七日来复，利有攸往。',
    daxiang: '雷在地中，复；先王以至日闭关，商旅不行，后不省方。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 一阳复始',
    interpretation: '一阳初动，寒极生春。转机已然在暗中萌发，状态回升，宜休整后重新启程，必见大好新局。',
    yi: '重启搁置项目、休整后出发、恢复锻炼、早起迎阳',
    ji: '悲观懈怠、急躁猛进、透支精力',
    luckyNumber: 1,
    luckyColor: '初阳橙',
    luckyCompass: '正东',
    stars: { fortune: 5, career: 4, wealth: 4, vitality: 5 }
  },
  // 29. 坎为水 010 010
  '010010': {
    id: 29,
    name: '坎为水',
    upperTrigram: '坎',
    lowerTrigram: '坎',
    binary: '010010',
    symbol: '䷜',
    nature: '水重洊至',
    classicQuote: '水底捞月',
    verse: '一重险水又一重，处险不惊守正公。常如止水照清影，终渡沧溟达天通。',
    guaci: '习坎，有孚，维心亨，行有尚。',
    daxiang: '水洊至，习坎；君子以常德行，习教事。',
    luckLevel: 'small',
    luckTitle: '小吉 · 履险如夷',
    interpretation: '重险之处见真功。心如止水，保持定力，以从容智慧稳步涉险，终能化险为夷、波澜不惊。',
    yi: '沉稳应对、步步为营、严密防护、多做备份',
    ji: '慌乱失措、盲目冒险、轻举妄动',
    luckyNumber: 6,
    luckyColor: '深海蓝',
    luckyCompass: '正北',
    stars: { fortune: 2, career: 3, wealth: 3, vitality: 4 }
  },
  // 30. 离为火 101 101
  '101101': {
    id: 30,
    name: '离为火',
    upperTrigram: '离',
    lowerTrigram: '离',
    binary: '101101',
    symbol: '䷝',
    nature: '重明继照',
    classicQuote: '天官赐福',
    verse: '天官赐福降祥光，两重明火耀明堂。文思泉涌才华展，吉曜临轩万事芳。',
    guaci: '利贞，亨。畜牝牛，吉。',
    daxiang: '明两作，离；大人以继明照于四方。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 重明继照',
    interpretation: '离者，丽也，明也。日月交辉，火光熊熊。思维灵感喷薄欲出，表达交流璀璨夺目。',
    yi: '技术分享、创作写作、设计前端、公开发表',
    ji: '虚荣张扬、暴躁发怒、情绪失控',
    luckyNumber: 9,
    luckyColor: '赤朱红',
    luckyCompass: '正南',
    stars: { fortune: 5, career: 5, wealth: 4, vitality: 5 }
  },
  // 42. 风雷益 100 011 (下震100，上巽011 -> 100011)
  '100011': {
    id: 42,
    name: '风雷益',
    upperTrigram: '巽',
    lowerTrigram: '震',
    binary: '100011',
    symbol: '䷩',
    nature: '风雷交加',
    classicQuote: '枯木开花',
    verse: '时来运转吉星照，枯木开花格外妖。风雷相济利攸往，大展宏图上青霄。',
    guaci: '利有攸往，利涉大川。',
    daxiang: '风雷，益；君子以见善则迁，有过则改。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 风雷大益',
    interpretation: '损上益下，民说无疆。顺风借力，正是扩充版图、进取跃升的大好良机，利于乘风破浪。',
    yi: '学习新技术、开启新计划、见善迁善、跑步健身',
    ji: '固步自封、推诿拖沓、裹足不前',
    luckyNumber: 4,
    luckyColor: '松石绿',
    luckyCompass: '东南',
    stars: { fortune: 5, career: 5, wealth: 5, vitality: 5 }
  },
  // 49. 泽火革 101 110 (下离101，上兑110 -> 101110)
  '101110': {
    id: 49,
    name: '泽火革',
    upperTrigram: '兑',
    lowerTrigram: '离',
    binary: '101110',
    symbol: '䷰',
    nature: '泽火交煎',
    classicQuote: '旱苗得雨',
    verse: '苗逢久旱忽逢霖，破旧立新自利身。革故鼎新成大器，光明灿烂换新春。',
    guaci: '己日乃孚，元亨利贞，悔亡。',
    daxiang: '泽中有火，革；君子以治历明时。',
    luckLevel: 'great',
    luckTitle: '上吉 · 革故鼎新',
    interpretation: '天地革而四时成。旧有瓶颈已到非破不可之时，勇于自我革命与突破，必将迎来新生与突破。',
    yi: '架构转型、更换工具流、果断斩断旧包袱、开拓思维',
    ji: '墨守成规、瞻前顾后、因循守旧',
    luckyNumber: 2,
    luckyColor: '琉璃橙',
    luckyCompass: '正南',
    stars: { fortune: 4, career: 5, wealth: 4, vitality: 4 }
  },
  // 50. 火风鼎 011 101 (下巽011，上离101 -> 011101)
  '011101': {
    id: 50,
    name: '火风鼎',
    upperTrigram: '离',
    lowerTrigram: '巽',
    binary: '011101',
    symbol: '䷱',
    nature: '木火相生',
    classicQuote: '渔翁得利',
    verse: '木火相生铸重器，鼎新自强得大成。稳步前行基业立，千秋伟业锦前程。',
    guaci: '元吉，亨。',
    daxiang: '木上有火，鼎；君子以正位凝命。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 鼎力革新',
    interpretation: '木上有火，亨饪也。调和百味以成盛宴。凝神静气，稳立根基，终成重器，大展鸿猷。',
    yi: '架构定型、结项验收、稳固基石、款待贵友',
    ji: '基石不稳、急功近利、三心二意',
    luckyNumber: 5,
    luckyColor: '古铜金',
    luckyCompass: '正南',
    stars: { fortune: 5, career: 5, wealth: 5, vitality: 5 }
  },
  // 51. 震为雷 100 100
  '100100': {
    id: 51,
    name: '震为雷',
    upperTrigram: '震',
    lowerTrigram: '震',
    binary: '100100',
    symbol: '䷲',
    nature: '洊雷发响',
    classicQuote: '金钟夜撞',
    verse: '金钟夜撞响当当，雷声百里振遐荒。临危不乱心从容，谈笑风生胜干强。',
    guaci: '亨。震来虩虩，笑言哑哑。震惊百里，不丧匕鬯。',
    daxiang: '洊雷，震；君子以恐惧修省。',
    luckLevel: 'great',
    luckTitle: '上吉 · 声威大振',
    interpretation: '震惊百里而不丧匕鬯。突发危机来临时临危不乱，从容处变，反而正是彰显真才实学的舞台。',
    yi: '直面突发Bug、泰然处事、迅速响应、反思修己',
    ji: '手忙脚乱、大惊小怪、推诿逃避',
    luckyNumber: 4,
    luckyColor: '雷光青',
    luckyCompass: '正东',
    stars: { fortune: 4, career: 5, wealth: 3, vitality: 5 }
  },
  // 52. 艮为山 001 001
  '001001': {
    id: 52,
    name: '艮为山',
    upperTrigram: '艮',
    lowerTrigram: '艮',
    binary: '001001',
    symbol: '䷳',
    nature: '兼山不动',
    classicQuote: '矮巴勾枣',
    verse: '兼山重叠路崎岖，行止分明守故居。知止不殆身常泰，静观万象得自如。',
    guaci: '艮其背，不获其身，行其庭，不见其人，无咎。',
    daxiang: '兼山，艮；君子以思不出其位。',
    luckLevel: 'peace',
    luckTitle: '吉平 · 止其所止',
    interpretation: '艮其止，止其所也。时止则止，时行则行。当止之处不可妄动，克制冲动，安心笃定。',
    yi: '守好本职、克制欲望、坐禅静养、梳理逻辑',
    ji: '越权插手、盲动跳槽、冲动发言',
    luckyNumber: 7,
    luckyColor: '岩石灰',
    luckyCompass: '东北',
    stars: { fortune: 3, career: 3, wealth: 3, vitality: 5 }
  },
  // 57. 巽为风 011 011
  '011011': {
    id: 57,
    name: '巽为风',
    upperTrigram: '巽',
    lowerTrigram: '巽',
    binary: '011011',
    symbol: '䷸',
    nature: '随风而入',
    classicQuote: '孤舟得水',
    verse: '随风潜入水云乡，柔顺谦逊福寿长。无孔不入谋算细，和风拂面送天香。',
    guaci: '小亨，利攸往，利见大人。',
    daxiang: '随风，巽；君子以申命行事。',
    luckLevel: 'great',
    luckTitle: '上吉 · 柔顺申命',
    interpretation: '风行天下，无微不至。以柔和细致之姿处理复杂细节，润物无声，化解摩擦，事半功倍。',
    yi: '细微处推敲、温和沟通、传达思想、整理代码',
    ji: '刚硬碰硬、粗枝大叶、武断决断',
    luckyNumber: 5,
    luckyColor: '柔翠色',
    luckyCompass: '东南',
    stars: { fortune: 4, career: 4, wealth: 4, vitality: 4 }
  },
  // 58. 兑为泽 110 110
  '110110': {
    id: 58,
    name: '兑为泽',
    upperTrigram: '兑',
    lowerTrigram: '兑',
    binary: '110110',
    symbol: '䷹',
    nature: '丽泽双融',
    classicQuote: '月里赏月',
    verse: '两泽相容喜气和，朋友切磋乐事多。谈笑风生皆有益，同舟共济度清波。',
    guaci: '亨，利贞。',
    daxiang: '丽泽，兑；君子以朋友讲习。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 丽泽讲习',
    interpretation: '兑者，说也，悦也。朋辈切磋，讲习明理，其乐融融。今日利于畅所欲言、学术讨论。',
    yi: '研讨交流、同行切磋、同好闲聊、分享技术',
    ji: '口无遮拦、刻薄讽刺、吹毛求疵',
    luckyNumber: 2,
    luckyColor: '银雪白',
    luckyCompass: '正西',
    stars: { fortune: 5, career: 5, wealth: 4, vitality: 5 }
  },
  // 63. 水火既济 101 010 (下离101，上坎010 -> 101010)
  '101010': {
    id: 63,
    name: '水火既济',
    upperTrigram: '坎',
    lowerTrigram: '离',
    binary: '101010',
    symbol: '䷾',
    nature: '水火交融',
    classicQuote: '金榜题名',
    verse: '金榜题名喜气新，十载寒窗始脱尘。所向皆谐谋事就，百福骈臻吉星临。',
    guaci: '亨小，利贞，初吉终乱。',
    daxiang: '水在火上，既济；君子以思患而预防之。',
    luckLevel: 'supreme',
    luckTitle: '大吉 · 功德圆满',
    interpretation: '阴阳各得其位，水火相交而济。大功告成，万事遂意，但宜居安思危、防微杜渐，善始善终。',
    yi: '交付大版本、项目结项、犒赏团队、复盘总结',
    ji: '得意忘形、忽视隐患、松懈懈怠',
    luckyNumber: 6,
    luckyColor: '碧玉色',
    luckyCompass: '正南',
    stars: { fortune: 5, career: 5, wealth: 5, vitality: 5 }
  },
  // 64. 火水未济 010 101 (下坎010，上离101 -> 010101)
  '010101': {
    id: 64,
    name: '火水未济',
    upperTrigram: '离',
    lowerTrigram: '坎',
    binary: '010101',
    symbol: '䷿',
    nature: '火在水上',
    classicQuote: '太公钓鱼',
    verse: '渭水钓璜待吉期，火水未济蓄英姿。莫道功成无指望，风云际会有期时。',
    guaci: '亨，小狐汔济，濡其尾，无攸利。',
    daxiang: '火在水上，未济；君子以慎辨物居方。',
    luckLevel: 'medium',
    luckTitle: '中吉 · 继往开来',
    interpretation: '未济者，无穷也。上一阶段暂落帷幕，全新起点正拉开序幕。保持初心，慎终如始，前途无量。',
    yi: '规划新起点、修整心态、准备启程、复盘思考',
    ji: '浅尝辄止、盲目自满、草率收尾',
    luckyNumber: 9,
    luckyColor: '绛紫色',
    luckyCompass: '正北',
    stars: { fortune: 4, career: 4, wealth: 3, vitality: 4 }
  }
}

// 补充全64卦通配回退生成器 (确保任意六爻二进制串 100% 具有严格对应的卦名、上下卦、卦辞、大象传与文王断)
export function getHexagramByBinary(binary: string): HexagramData {
  if (HEXAGRAM_DATABASE[binary]) {
    return HEXAGRAM_DATABASE[binary]
  }

  // 若不在高频精录表中，根据严格上下三爻解析八经卦，动态生成周易古法标准卦
  const lowerBits = binary.slice(0, 3)
  const upperBits = binary.slice(3, 6)

  const lowerTrigram = TRIGRAM_MAP[lowerBits] || { name: '坤', element: '地', symbol: '☷' }
  const upperTrigram = TRIGRAM_MAP[upperBits] || { name: '乾', element: '天', symbol: '☰' }

  const nature = `${upperTrigram.element}上${lowerTrigram.element}下`

  return {
    id: 99,
    name: `${upperTrigram.name}${lowerTrigram.name === upperTrigram.name ? '为' + upperTrigram.element : lowerTrigram.name}`,
    upperTrigram: upperTrigram.name,
    lowerTrigram: lowerTrigram.name,
    binary,
    symbol: '䷀',
    nature,
    classicQuote: '文王神机',
    verse: `上${upperTrigram.element}下${lowerTrigram.element}吉运彰，阴阳交会自荣昌。秉公持正行大道，步步升迁纳吉祥。`,
    guaci: '元亨利贞，顺时守正，无咎。',
    daxiang: `${upperTrigram.element}在${lowerTrigram.element}上，君子以顺天应人，自强不息。`,
    luckLevel: 'great',
    luckTitle: '上吉 · 乾坤并济',
    interpretation: `由下卦【${lowerTrigram.name}】与上卦【${upperTrigram.name}】相叠而成。阴阳得位，中正通达，以德行立身，顺乎天理，凡谋皆吉。`,
    yi: '顺应时势、沉潜笃行、恪守正道、请客饮茶',
    ji: '违逆规律、急功近利、与人交恶',
    luckyNumber: 6,
    luckyColor: '青金石色',
    luckyCompass: '东南',
    stars: { fortune: 4, career: 4, wealth: 4, vitality: 4 }
  }
}
